name: Addon数据迁移工具
version: 0.2.1
slug: addonDataMigrate
codenotary: wghaos@163.com
description: '解决不同仓库中addons的数据迁移'
url: https://gitcode.com/waxgourd/addons
image: wghaos/addon-data-migrate
init: false
arch:
  - aarch64
  - amd64
  - armv7
ingress: true
ingress_port: 80
map:
  - all_addon_configs:rw
  - backup:rw
apparmor: false
docker_api: true
startup: services
boot: manual
